[[redirects]]
  from = "/404.html"
  to = "/404/"
  status = 404
  force = true

[[redirects]]
  from = "/404"
  to = "/asd/"
  status = 404
  force = true

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404
